package projekakhirpbo23;

import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;

public class admin extends javax.swing.JFrame {
    
    public Connection con;
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel model;
    
    public admin() {
        initComponents();
        String[] header = {"ID","Film","Waktu","Room","Harga"}; //membuat header tabel
        model = new DefaultTableModel(header,0);
        tabel.setModel(model);
        tampil();
    }
    
    public void tampil(){ 
        
        koneksi konek = new koneksi(); //memanggil class koneksi dan menjadikan objek
        int jumlahrow = tabel.getRowCount();
        for(int n=0;n<jumlahrow;n++){
        model.removeRow(0);
        }
       //V1
       /* try{
            con = konek.getKoneksi();
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM film"); 
            while(rs.next()){
                String[] row = {Integer.toString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5)};
                model.addRow(row);
            }
        tabel.setModel(model);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }*/
      //V2
      
      /*model.addColumn("ID");
      model.addColumn("Film");
      model.addColumn("Waktu");
      model.addColumn("Room");
      model.addColumn("Harga");
      tabel.setModel(model); 
      
      try{
      con = konek.getKoneksi();
      st=con.createStatement();    
      rs=st.executeQuery("SELECT * FROM film");
      while(rs.next()){
          model.addRow(new Object[]{
          rs.getString("id"),
          rs.getString("film"),
          rs.getString("waktu"),
          rs.getString("room"),
          rs.getString("harga"),
          });
        }
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, "Gagal");
      }*/
      
      //V3
      try{
            con = konek.getKoneksi(); //membuka data di db pada tabel film
            st = con.createStatement();
            rs = st.executeQuery("SELECT * FROM film"); 
            while(rs.next()){
                    model.addRow(new Object[]{
                    rs.getString("id_film"),
                    rs.getString("nama_film"),
                    rs.getString("waktu"),
                    rs.getString("room"),
                    rs.getString("harga"),
                });
            }
        }catch(SQLException ex){
         System.out.println(ex.getMessage());
      }
    }
    
    public void tambah(){ //fungsi tambah data
        String id = tfid.getText();
        String film = tffilm.getText();
        String waktu = tfwaktu.getText();
        String harga = tfharga.getText();
        String room = tfruangan.getText();

        koneksi konek = new koneksi();
        try{
            con = konek.getKoneksi();
            st = con.createStatement();
            st.execute("INSERT INTO film VALUES (NULL,'"+film+"','"+waktu+"','"+room+"','"+harga+"')");
            JOptionPane.showMessageDialog(null, "Berhasil","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        tambah = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        tffilm = new javax.swing.JTextField();
        tfwaktu = new javax.swing.JTextField();
        tfruangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        riwayat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lid = new javax.swing.JLabel();
        tfid = new javax.swing.JTextField();
        admin2 = new gambar.admin();
        tfharga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Film", "Waktu", "Room", "Harga"
            }
        ));
        tabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 510, 240));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 83, -1));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 83, -1));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 83, -1));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 83, -1));

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));
        getContentPane().add(tffilm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 145, -1));
        getContentPane().add(tfwaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 145, -1));
        getContentPane().add(tfruangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, 145, -1));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 102));
        jLabel2.setText("Film");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 58, -1));

        riwayat.setText("Riwayat");
        riwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                riwayatActionPerformed(evt);
            }
        });
        getContentPane().add(riwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 80, -1));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 51));
        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 58, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 104, -1, -1));
        getContentPane().add(lid, new org.netbeans.lib.awtextra.AbsoluteConstraints(829, 104, -1, -1));
        getContentPane().add(tfid, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 146, -1));

        tfharga.setCaretColor(new java.awt.Color(1, 1, 1));

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 51));
        jLabel5.setText("Harga");

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 51));
        jLabel4.setText("Room");

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 51));
        jLabel3.setText("Waktu");

        javax.swing.GroupLayout admin2Layout = new javax.swing.GroupLayout(admin2);
        admin2.setLayout(admin2Layout);
        admin2Layout.setHorizontalGroup(
            admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Layout.createSequentialGroup()
                .addContainerGap(570, Short.MAX_VALUE)
                .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        admin2Layout.setVerticalGroup(
            admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin2Layout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(admin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(92, 92, 92))
        );

        getContentPane().add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        tambah(); //memanggil fungsi tambah yang ada di atas
        tampil(); //memanggil fungsi tampil yang ada di atas
    }//GEN-LAST:event_tambahActionPerformed
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       tfid.setText(""); //untuk reset
       tffilm.setText("");
       tfwaktu.setText("");
       tfharga.setText("");
       tfruangan.setText("");
    }//GEN-LAST:event_resetActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        String id = tfid.getText(); //delete
        int cek = JOptionPane.showConfirmDialog(null, "Yakin?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if(cek==0){
            try {
                String sql = "DELETE FROM film WHERE id_film='"+id+"'";
                PreparedStatement pr = con.prepareStatement(sql);
                pr.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sukses");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal");
            }
        }
        
        tampil();
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        koneksi konek = new koneksi(); //update
        con = konek.getKoneksi();
        String id = tfid.getText();
        String film = tffilm.getText();
        String waktu = tfwaktu.getText();
        String harga = tfharga.getText();
        String ruangan = tfruangan.getText();
        
        try{
            st=con.createStatement();
            st.execute("UPDATE film SET nama_film='"+film+"', waktu='"+waktu+"', room='"+ruangan+"', harga='"+harga+"' WHERE id_film='"+id+"'");
            JOptionPane.showMessageDialog(null,"Berhasil");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error","Error",JOptionPane.WARNING_MESSAGE);
        }
        tampil();
    }//GEN-LAST:event_updateActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        new login().show(); //untuk kembali ke login
        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void riwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_riwayatActionPerformed
        new riwayat().show(); //untuk ke menu riwayat
        this.dispose();
    }//GEN-LAST:event_riwayatActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        int baris = tabel.rowAtPoint(evt.getPoint()); //untuk menampilkan data yang ada di tabel ke text field
        String id = tabel.getValueAt(baris, 0).toString();
        tfid.setText(id);

        String film = tabel.getValueAt(baris, 1).toString();
        tffilm.setText(film);

        String waktu = tabel.getValueAt(baris, 2).toString();
        tfwaktu.setText(waktu);

        String room = tabel.getValueAt(baris, 3).toString();
        tfruangan.setText(room);

        String harga = tabel.getValueAt(baris, 4).toString();
        tfharga.setText(harga);
    }//GEN-LAST:event_tabelMouseClicked

    private void tabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gambar.admin admin2;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel lid;
    private javax.swing.JButton reset;
    private javax.swing.JButton riwayat;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField tffilm;
    private javax.swing.JTextField tfharga;
    private javax.swing.JTextField tfid;
    private javax.swing.JTextField tfruangan;
    private javax.swing.JTextField tfwaktu;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
